submit: True
name: gru_ae_week_event_cat_price_sku_url
cuda_visible_devices: 0

clearml_project:
clearml_task:

data_path_raw: ${oc.env:CHALLENGE_DATA_PATH}/raw
save_path: ${oc.env:CHALLENGE_DATA_PATH}

data:
  relevant: true
  max_count: 5000
  use_columns:
  - week
  - event_type
  - category
  - price
  - sku
  - url

dataset:
  max_length: 128

dataloader:
  batch_size: 256
  test_batch_size: 256
  num_workers: 8

model_params:
  embedding_dim: 512
  hidden_size: 512
  num_layers: 3
  dropout: 0.1

training_params:
  lr: 0.001

trainer_params:
  max_epochs: 10
  devices: 1
patience: 3