submit: True
name: gru_ae_day_event
cuda_visible_devices: 0

clearml_project:
clearml_task:

data_path_raw: ${oc.env:CHALLENGE_DATA_PATH}/raw
save_path: ${oc.env:CHALLENGE_DATA_PATH}

data:
  relevant: True

dataset:
  max_length: 128

dataloader:
  batch_size: 256
  test_batch_size: 256
  num_workers: 8

model_params:
  embedding_dim: 64
  hidden_size: 128
  num_layers: 2
  dropout: 0.5

training_params:
  lr: 0.001

trainer_params:
  max_epochs: 30
  devices: 1
patience: 5
